-- SkillBharat core schema (PostgreSQL)

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(190) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    full_name      VARCHAR(120) NOT NULL,
    phone          VARCHAR(20),
    role           VARCHAR(20)  NOT NULL CHECK (role IN ('JOB_SEEKER', 'EMPLOYER', 'ADMIN')),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at  TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));
CREATE INDEX idx_users_role ON users (role);

CREATE TABLE skills (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(80) NOT NULL UNIQUE,
    category  VARCHAR(60) NOT NULL
);
CREATE INDEX idx_skills_category ON skills (category);

CREATE TABLE candidate_profiles (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT      NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    headline                VARCHAR(150),
    city                    VARCHAR(80),
    state                   VARCHAR(80),
    summary                 TEXT,
    total_experience_years  INTEGER,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE candidate_skills (
    profile_id  BIGINT NOT NULL REFERENCES candidate_profiles (id) ON DELETE CASCADE,
    skill_id    BIGINT NOT NULL REFERENCES skills (id),
    PRIMARY KEY (profile_id, skill_id)
);

CREATE TABLE educations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id          BIGINT       NOT NULL REFERENCES candidate_profiles (id) ON DELETE CASCADE,
    degree              VARCHAR(120) NOT NULL,
    institution         VARCHAR(150),
    year_of_completion  INTEGER
);
CREATE INDEX idx_educations_profile ON educations (profile_id);

CREATE TABLE experiences (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id    BIGINT       NOT NULL REFERENCES candidate_profiles (id) ON DELETE CASCADE,
    job_title     VARCHAR(120) NOT NULL,
    company_name  VARCHAR(150),
    start_date    DATE,
    end_date      DATE,
    description   TEXT
);
CREATE INDEX idx_experiences_profile ON experiences (profile_id);

CREATE TABLE resumes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id         BIGINT       NOT NULL REFERENCES candidate_profiles (id) ON DELETE CASCADE,
    original_filename  VARCHAR(255) NOT NULL,
    storage_key        VARCHAR(120) NOT NULL UNIQUE,
    content_type       VARCHAR(100) NOT NULL,
    size_bytes         BIGINT       NOT NULL,
    uploaded_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_resumes_profile ON resumes (profile_id);

CREATE TABLE companies (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id          BIGINT       NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    name              VARCHAR(150) NOT NULL,
    description       TEXT,
    industry          VARCHAR(100),
    city              VARCHAR(80),
    state             VARCHAR(80),
    website           VARCHAR(200),
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    rejection_reason  VARCHAR(500),
    reviewed_at       TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_companies_status ON companies (status);

CREATE TABLE jobs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            BIGINT       NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    title                 VARCHAR(150) NOT NULL,
    description           TEXT         NOT NULL,
    category              VARCHAR(60)  NOT NULL,
    city                  VARCHAR(80)  NOT NULL,
    state                 VARCHAR(80)  NOT NULL,
    job_type              VARCHAR(20)  NOT NULL CHECK (job_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'APPRENTICE')),
    salary_min            INTEGER,
    salary_max            INTEGER,
    min_experience_years  INTEGER      NOT NULL DEFAULT 0,
    openings              INTEGER      NOT NULL DEFAULT 1,
    status                VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'
                          CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    rejection_reason      VARCHAR(500),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    posted_at             TIMESTAMPTZ
);
CREATE INDEX idx_jobs_company ON jobs (company_id);
CREATE INDEX idx_jobs_status_active ON jobs (status, active);
CREATE INDEX idx_jobs_category ON jobs (category);
CREATE INDEX idx_jobs_city ON jobs (lower(city));

CREATE TABLE job_skills (
    job_id    BIGINT NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    skill_id  BIGINT NOT NULL REFERENCES skills (id),
    PRIMARY KEY (job_id, skill_id)
);

CREATE TABLE applications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      BIGINT       NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    profile_id  BIGINT       NOT NULL REFERENCES candidate_profiles (id) ON DELETE CASCADE,
    resume_id   BIGINT       REFERENCES resumes (id) ON DELETE SET NULL,
    cover_note  VARCHAR(1000),
    status      VARCHAR(20)  NOT NULL DEFAULT 'APPLIED' CHECK (status IN ('APPLIED', 'SHORTLISTED', 'REJECTED')),
    applied_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_application_job_profile UNIQUE (job_id, profile_id)
);
CREATE INDEX idx_applications_job ON applications (job_id);
CREATE INDEX idx_applications_profile ON applications (profile_id);
CREATE INDEX idx_applications_status ON applications (status);

CREATE TABLE saved_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT      NOT NULL REFERENCES candidate_profiles (id) ON DELETE CASCADE,
    job_id      BIGINT      NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    saved_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_saved_job_profile UNIQUE (profile_id, job_id)
);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT,
    actor_email  VARCHAR(190),
    action       VARCHAR(60)  NOT NULL,
    entity_type  VARCHAR(40)  NOT NULL,
    entity_id    BIGINT,
    details      VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_created ON audit_logs (created_at DESC);
