-- Reference data: skills grouped by trade category
INSERT INTO skills (name, category) VALUES
    ('Domestic Wiring', 'Electrical & Electronics'),
    ('Industrial Wiring', 'Electrical & Electronics'),
    ('Panel Board Assembly', 'Electrical & Electronics'),
    ('Solar PV Installation', 'Electrical & Electronics'),
    ('CCTV & Security Systems', 'Electrical & Electronics'),
    ('Motor Winding', 'Electrical & Electronics'),
    ('Inverter & UPS Repair', 'Electrical & Electronics'),
    ('Pipe Fitting', 'Plumbing & Sanitation'),
    ('Bathroom Fitting', 'Plumbing & Sanitation'),
    ('Water Pump Maintenance', 'Plumbing & Sanitation'),
    ('Drainage & Sewer Work', 'Plumbing & Sanitation'),
    ('Arc Welding', 'Welding & Fabrication'),
    ('MIG Welding', 'Welding & Fabrication'),
    ('TIG Welding', 'Welding & Fabrication'),
    ('Sheet Metal Fabrication', 'Welding & Fabrication'),
    ('Structural Fabrication', 'Welding & Fabrication'),
    ('Gas Cutting', 'Welding & Fabrication'),
    ('Carpentry', 'Carpentry & Furniture'),
    ('Modular Furniture Fitting', 'Carpentry & Furniture'),
    ('Wood Polishing', 'Carpentry & Furniture'),
    ('Door & Window Fitting', 'Carpentry & Furniture'),
    ('Masonry', 'Construction & Civil'),
    ('Tile & Marble Fitting', 'Construction & Civil'),
    ('Painting & Finishing', 'Construction & Civil'),
    ('Shuttering & Bar Bending', 'Construction & Civil'),
    ('Site Supervision', 'Construction & Civil'),
    ('False Ceiling & POP', 'Construction & Civil'),
    ('Two-Wheeler Mechanic', 'Automotive & Mechanic'),
    ('Four-Wheeler Mechanic', 'Automotive & Mechanic'),
    ('Auto Electrician', 'Automotive & Mechanic'),
    ('Denting & Painting', 'Automotive & Mechanic'),
    ('Wheel Alignment', 'Automotive & Mechanic'),
    ('Diesel Engine Repair', 'Automotive & Mechanic'),
    ('CNC Operator', 'CNC & Machine Operation'),
    ('VMC Operator', 'CNC & Machine Operation'),
    ('Lathe Machine Operator', 'CNC & Machine Operation'),
    ('Milling Machine Operator', 'CNC & Machine Operation'),
    ('Quality Inspection', 'CNC & Machine Operation'),
    ('Fitter', 'CNC & Machine Operation'),
    ('AC Installation & Repair', 'HVAC & Refrigeration'),
    ('Refrigerator Repair', 'HVAC & Refrigeration'),
    ('Chiller Maintenance', 'HVAC & Refrigeration'),
    ('Cold Room Maintenance', 'HVAC & Refrigeration'),
    ('Heavy Vehicle Driver', 'Driving & Logistics'),
    ('Light Vehicle Driver', 'Driving & Logistics'),
    ('Forklift Operator', 'Driving & Logistics'),
    ('Delivery Executive', 'Driving & Logistics'),
    ('Warehouse Associate', 'Driving & Logistics'),
    ('Commis Chef', 'Hospitality & Kitchen'),
    ('Tandoor Cook', 'Hospitality & Kitchen'),
    ('Kitchen Helper', 'Hospitality & Kitchen'),
    ('Restaurant Steward', 'Hospitality & Kitchen'),
    ('Housekeeping Attendant', 'Hospitality & Kitchen'),
    ('Security Guard', 'Security & Facility'),
    ('Facility Supervisor', 'Security & Facility'),
    ('Lift Operator', 'Security & Facility'),
    ('Fire Safety Technician', 'Security & Facility'),
    ('Tailoring', 'Tailoring & Textile'),
    ('Embroidery', 'Tailoring & Textile'),
    ('Pattern Cutting', 'Tailoring & Textile'),
    ('Garment Finishing', 'Tailoring & Textile'),
    ('Knitting Machine Operator', 'Tailoring & Textile'),
    ('Hair Stylist', 'Beauty & Wellness'),
    ('Beautician', 'Beauty & Wellness'),
    ('Mehendi Artist', 'Beauty & Wellness'),
    ('Spa Therapist', 'Beauty & Wellness'),
    ('Retail Sales Associate', 'Retail & Sales'),
    ('Field Sales Executive', 'Retail & Sales'),
    ('Store Keeper', 'Retail & Sales'),
    ('Cashier', 'Retail & Sales'),
    ('Data Entry Operator', 'Office & IT Support'),
    ('Computer Hardware Repair', 'Office & IT Support'),
    ('Network Cabling', 'Office & IT Support'),
    ('Tally & Accounts Assistant', 'Office & IT Support'),
    ('Mobile Phone Repair', 'Office & IT Support');
